name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        run: sudo apt-get install php
      - name: Install Composer
        run: composer install
      - name: Build PHP code
        run: php artisan build
      - name: Run unit tests
        run: php vendor/bin/phpunit
      - name: Deploy to FTP
        run: php artisan deploy
