name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Building code..."
          php composer.phar install
          php artisan migrate
          php artisan serve
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Testing code..."
          phpunit
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Deploying code..."
          scp -r ./public/ ftp://epiz_34203858:COifH15wVgtu@ftpupload.net/public_html/
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event.branch == 'master'
    needs: [build, test, deploy]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Deploying code to staging..."
          scp -r ./public/ ftp://epiz_34203858:COifH15wVgtu@ftpupload.net/public_html/staging/
